// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using dev.studio.Server.DAL;

#nullable disable

namespace dev.studio.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241002044944_AppEntityAttr_ExtRef")]
    partial class AppEntityAttr_ExtRef
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("dev.studio.Server.DAL.Models.AppDataType", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PgType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppDataTypes");
                });

            modelBuilder.Entity("dev.studio.Server.DAL.Models.AppEntity", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int?>("AppModuleId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppModuleId");

                    b.ToTable("AppEntities");
                });

            modelBuilder.Entity("dev.studio.Server.DAL.Models.AppEntityAttribute", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int>("AppDataTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("AppEntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DbColumnDefaultValue")
                        .HasColumnType("text");

                    b.Property<int?>("DbColumnLength")
                        .HasColumnType("integer");

                    b.Property<string>("DbColumnName")
                        .HasColumnType("text");

                    b.Property<int?>("DbColumnPrecision")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ExtReferenceId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsNullable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimaryKey")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSearchable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUnique")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppDataTypeId");

                    b.HasIndex("AppEntityId");

                    b.HasIndex("ExtReferenceId");

                    b.ToTable("AppEntityAttributes");
                });

            modelBuilder.Entity("dev.studio.Server.DAL.Models.AppModule", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("OltpModuleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchemaName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppModules");
                });

            modelBuilder.Entity("dev.studio.Server.DAL.Models.SystemConfig", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("SimpleValue")
                        .HasColumnType("text");

                    b.Property<JsonDocument>("Value")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("SystemConfigs");
                });

            modelBuilder.Entity("dev.studio.Server.DAL.Models.AppEntity", b =>
                {
                    b.HasOne("dev.studio.Server.DAL.Models.AppModule", "AppModule")
                        .WithMany("AppEntities")
                        .HasForeignKey("AppModuleId");

                    b.Navigation("AppModule");
                });

            modelBuilder.Entity("dev.studio.Server.DAL.Models.AppEntityAttribute", b =>
                {
                    b.HasOne("dev.studio.Server.DAL.Models.AppDataType", "AppDataType")
                        .WithMany()
                        .HasForeignKey("AppDataTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dev.studio.Server.DAL.Models.AppEntity", "AppEntity")
                        .WithMany("AppEntityAttributes")
                        .HasForeignKey("AppEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dev.studio.Server.DAL.Models.AppEntityAttribute", "ExtReference")
                        .WithMany()
                        .HasForeignKey("ExtReferenceId");

                    b.Navigation("AppDataType");

                    b.Navigation("AppEntity");

                    b.Navigation("ExtReference");
                });

            modelBuilder.Entity("dev.studio.Server.DAL.Models.AppEntity", b =>
                {
                    b.Navigation("AppEntityAttributes");
                });

            modelBuilder.Entity("dev.studio.Server.DAL.Models.AppModule", b =>
                {
                    b.Navigation("AppEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
